### ISSUE TITLE
Changing engine properties inside slots

### ISSUE THREAD

**Issue by flanfly** [White-Oak/qml-rust#22]
I'm looking into replacing qmlrs with qml-rust in one of my projects. The backend of the application exposes its data using a bunch of `QListModel` instances to the fontend written in QML. When to user kicks off an action the QML side calls a slot of a singleton object. The slot handler code on the Rust side will do his thing and then update some of the `QListModel` instances and return. My problem is that I can't figure out how to get a hold of a reference to the `QListModel`s. I tried to make them properties of the singleton which failed, I also had the idea to put the `QmlEngine` instance into a global static `RwLock`. Any ideas?

**Comment by White-Oak** [comment]
@flanfly Well, one of my app (it's pretty simple) `Kefia` uses `QListModel` as a data storage.

It uses a following approach:
- There is a field `list` in a [`Packages` struct](https://github.com/White-Oak/kefia/blob/master/src/view.rs#L64-L72) which is essentially a `QListModel` instance inside. (It is generated though `Q_LIST_MODEL` macro [here](https://github.com/White-Oak/kefia/blob/master/src/view.rs#L48-L54) 
- When user interacts with a list, QML rings a [slot](https://github.com/White-Oak/kefia/blob/master/src/view.rs#L104) of `QPackages` (that is a wrapper on the `Packages` struct).
- Rust code modifies a list with a calculated data [via `set_data`](https://github.com/White-Oak/kefia/blob/master/src/view.rs#L142)
  So, the `QListModel` instance should be stored inside a model, but not as a property, but as a field of a struct.

That is what we have for now. I hope I described it okayish.

**Comment by White-Oak** [comment]
Also, properties are supported, but it is not really comfortable to use them due to limitations of macro system on stable Rust.

**Comment by flanfly** [comment]
Thanks for the quick answer! I did not know I have to write `list` instead of `QListModel` into the macro. I'll try that.

**Comment by White-Oak** [comment]
@flanfly you don't have to name it list, actually, any valid Rust identifier is good. [Here are the docs with an example](https://white-oak.github.io/qml-rust/qml/macro.Q_LISTMODEL.html)

**Comment by flanfly** [comment]
I got it to work, thanks.
