### ISSUE TITLE
Enum registering?

### ISSUE THREAD

**Issue by bzar** [White-Oak/qml-rust#24]
I tried to find how to register [enums](http://doc.qt.io/qt-5/qml-enumeration.html), but couldn't see any indication of support for such in the examples nor the code. Is there a preferred workaround for this?

**Comment by White-Oak** [comment]
@bzar no, qml-rust does not support registering enums. Is it needed? Why not define enums in QML code?

**Comment by bzar** [comment]
Well, because they're already defined in another part of the application. I'm creating a thin translation layer for a library to be usable from a QML UI. Much of the library's interface depends on various enums, and not being able to register them directly results in either multiple versions of the same function to cover all the cases or creating some ugly magic number/string based enum emulation. This is only a doodle, so nothing of importance is lost for me  if there's no enum support, just wanted to ask if there's a way to do this. Thanks for the quick reply.

**Comment by White-Oak** [comment]
@bzar sorry for the inconvenience
